config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :fourth_tests do
      resources :fourth_reviews
      resources :sixth_reviews
      resources :fifth_reviews
        end
    resources :third_tests do 
      resources :third_reviews
    end
    resources :second_tests do
      resources :second_reviews
    end
    resources :first_tests do
      resources :first_reviews
    end
  end

  

end

app/models/fifth_review.rb
class FifthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/first_review.rb
class FirstReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :first_test
end

app/models/first_test.rb
class FirstTest < ActiveRecord::Base
  belongs_to :user
  has_many :first_reviews, dependent: :destroy
  mount_uploader :info1
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.first_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fourth_review.rb
class FourthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/fourth_test.rb
class FourthTest < ActiveRecord::Base
  belongs_to :user
  has_many :fourth_reviews, dependent: :destroy
  has_many :fifth_reviews, dependent: :destroy
  has_many :sixth_reviews, dependent: :destroy
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.fourth_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fouth_review.rb
class FouthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/second_review.rb
class SecondReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :second_test
end

app/models/second_test.rb
class SecondTest < ActiveRecord::Base
  belongs_to :user
  has_many :second_reviews, dependent: :destroy
  mount_uploader :boceto
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.second_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/sixth_review.rb
class SixthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/third_review.rb
class ThirdReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :third_test
end

app/models/third_test.rb
class ThirdTest < ActiveRecord::Base
  belongs_to :user
  has_many :third_reviews, dependent: :destroy
  mount_uploader :info2
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.third_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :first_tests, dependent: :destroy
  has_many :second_tests, dependent: :destroy
  has_many :third_tests, dependent: :destroy
  has_many :fourth_tests, dependent: :destroy
  has_many :first_reviews, through: :tests, dependent: :destroy
  has_many :second_reviews, through: :tests, dependent: :destroy
  has_many :third_reviews, through: :tests, dependent: :destroy
  has_many :fourth_reviews, through: :tests, dependent: :destroy
  has_many :fifth_reviews, through: :tests, dependent: :destroy
  has_many :sixth_reviews, through: :tests, dependent: :destroy
end

app/controllers/second_tests_controller.rb
class SecondTestsController < ApplicationController
  before_action :set_second_test, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  before_action :authenticate_user!

  # GET /second_tests
  # GET /second_tests.json
  def index
    @second_tests = SecondTest.all
    @second_testa = current_user.second_tests
  end

  # GET /second_tests/1
  # GET /second_tests/1.json
  def show
        if @second_test.second_reviews.blank?
      @avg_problema1=0
      @avg_cliente1=0
      @avg_alternativa1=0
      @avg_solucion1=0
      @avg_ventajas1=0
    else
      @avg_problema1=@second_test.second_reviews.average(:problema1).round(2)
      @avg_cliente1=@second_test.second_reviews.average(:cliente1).round(2)
      @avg_alternativa1=@second_test.second_reviews.average(:alternativa1).round(2)
      @avg_solucion1=@second_test.second_reviews.average(:solucion1).round(2)
      @avg_ventajas1=@second_test.second_reviews.average(:ventajas1).round(2)
    end
  end

  # GET /second_tests/new
  def new
    @second_test = SecondTest.new
  end

  # GET /second_tests/1/edit
  def edit
  end

  # POST /second_tests
  # POST /second_tests.json
  def create
    @second_test = SecondTest.new(second_test_params)
    @second_test.user_id=current_user.id

    if @second_test.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  # PATCH/PUT /second_tests/1
  # PATCH/PUT /second_tests/1.json
  def update
    respond_to do |format|
      if @second_test.update(second_test_params)
        format.html { redirect_to @user, notice: 'Second test was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @second_test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /second_tests/1
  # DELETE /second_tests/1.json
  def destroy
    @second_test.destroy
    respond_to do |format|
      format.html { redirect_to second_tests_url, notice: 'Second test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_second_test
      @second_test = SecondTest.find(params[:id])
    end
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def second_test_params
      params.require(:second_test).permit(:boceto, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.where(admin: false).order("team asc")
    @usera = User.where(id: current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all.includes(:first_tests, :second_tests, :third_tests, :fourth_tests)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :admin, :team, :inte1, :inte2, :inte3, :inte4, :inte5, :cuenta1, :cuenta2, :cuenta3, :cuenta4, :cuenta5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fifth_reviews_helper.rb
module FifthReviewsHelper
end

app/helpers/first_reviews_helper.rb
module FirstReviewsHelper
end

app/helpers/first_tests_helper.rb
module FirstTestsHelper
end

app/helpers/fourth_tests_helper.rb
module FourthTestsHelper
end

app/helpers/second_tests_helper.rb
module SecondTestsHelper
end

app/helpers/third_tests_helper.rb
module ThirdTestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/second_tests/_form.html.erb
<%= form_for([@user, @second_test]) do |f| %>
  <% if @second_test.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@second_test.errors.count, "error") %> prohibited this second_test from being saved:</h2>

      <ul>
      <% @second_test.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2>Fase <strong>2. PROPUESTA PRELIMINAR DE SOLUCIÓN</strong></h2>
  <hr class="blue">
<p class="center">Adjunta el archivo del Boceto de idea. </p>

  <div class="field">
    <%= f.label :Boceto_de_idea %><br>
    <%= @second_test.boceto if @second_test.boceto %> <br><br>
    <%= f.file_field :boceto %>
    <%= f.hidden_field :boceto_cache %>
  </div>
  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/second_tests/edit.html.erb
<div class="col-sm-10 col-sm-offset-1">
	<div id="formario">

<%= render 'form' %>

<%= link_to 'Atrás', user_path(@user) %>
	</div>
</div>

app/views/second_tests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Second Tests</h1>

<table>
  <thead>
    <tr>
      <th>Boceto</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @second_tests.each do |second_test| %>
      <tr>
        <td><%= second_test.boceto %></td>
        <td><%= second_test.user %></td>
        <td><%= link_to 'Show', second_test(@second_test) %></td>
        <td><%= link_to 'Edit', edit_second_test_path(second_test) %></td>
        <td><%= link_to 'Destroy', second_test, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Second test', new_second_test_path %>

app/views/second_tests/new.html.erb
<div class="col-sm-10 col-sm-offset-1">
	<div id="formario">

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>
	</div>
</div>

app/views/second_tests/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-10 col-sm-offset-1">
  <div id="formario">

    <p>
      <strong>Equipo:</strong>
      <%= @second_test.user.team %>
    </p>

    <p>
      <strong>Boceto de Idea:</strong>
      <%= @second_test.boceto %>
    </p>
<%= link_to "Descargar Boceto de Idea", @second_test.boceto_url %>
<br><br>


    <table>
      <thead>
        <tr>
          <th>Problema</th>
          <th>Cliente</th>
          <th>Alternativas Existentes</th>
          <th>Solución</th>
          <th>Ventajas Competitivas diferenciadoras</th>
          <th colspan="5"></th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td><%=@avg_problema1%></td>
          <td><%=@avg_cliente1%></td>
          <td><%=@avg_alternativa1%></td>
          <td><%=@avg_solucion1%></td>
          <td><%=@avg_ventajas1%></td>
        </tr>
      </tbody>
      <em><%= "#{@second_test.second_reviews.length} calificaciones promediadas" %></em>
    </table><br><br>


    <%= link_to "Escribir nueva calificación", new_user_second_test_second_review_path(@user, @second_test) %>
<br><br>
    <%= link_to 'Atrás', user_path(@user) %>

  </div>
</div>