config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :fourth_tests do
      resources :fourth_reviews
      resources :sixth_reviews
      resources :fifth_reviews
        end
    resources :third_tests do 
      resources :third_reviews
    end
    resources :second_tests do
      resources :second_reviews
    end
    resources :first_tests do
      resources :first_reviews
    end
  end

  

end

app/models/fifth_review.rb
class FifthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/first_review.rb
class FirstReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :first_test
end

app/models/first_test.rb
class FirstTest < ActiveRecord::Base
  belongs_to :user
  has_many :first_reviews, dependent: :destroy
  mount_uploader :info1
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.first_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fourth_review.rb
class FourthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/fourth_test.rb
class FourthTest < ActiveRecord::Base
  belongs_to :user
  has_many :fourth_reviews, dependent: :destroy
  has_many :fifth_reviews, dependent: :destroy
  has_many :sixth_reviews, dependent: :destroy
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.fourth_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fouth_review.rb
class FouthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/second_review.rb
class SecondReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :second_test
end

app/models/second_test.rb
class SecondTest < ActiveRecord::Base
  belongs_to :user
  has_many :second_reviews, dependent: :destroy
  mount_uploader :boceto
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.second_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/sixth_review.rb
class SixthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/third_review.rb
class ThirdReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :third_test
end

app/models/third_test.rb
class ThirdTest < ActiveRecord::Base
  belongs_to :user
  has_many :third_reviews, dependent: :destroy
  mount_uploader :info2
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.third_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :first_tests, dependent: :destroy
  has_many :second_tests, dependent: :destroy
  has_many :third_tests, dependent: :destroy
  has_many :fourth_tests, dependent: :destroy
  has_many :first_reviews, through: :tests, dependent: :destroy
  has_many :second_reviews, through: :tests, dependent: :destroy
  has_many :third_reviews, through: :tests, dependent: :destroy
  has_many :fourth_reviews, through: :tests, dependent: :destroy
  has_many :fifth_reviews, through: :tests, dependent: :destroy
  has_many :sixth_reviews, through: :tests, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.where(admin: false).order("team asc")
    @usera = User.where(id: current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all.includes(:first_tests, :second_tests, :third_tests, :fourth_tests)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :admin, :team, :inte1, :inte2, :inte3, :inte4, :inte5, :cuenta1, :cuenta2, :cuenta3, :cuenta4, :cuenta5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fifth_reviews_helper.rb
module FifthReviewsHelper
end

app/helpers/first_reviews_helper.rb
module FirstReviewsHelper
end

app/helpers/first_tests_helper.rb
module FirstTestsHelper
end

app/helpers/fourth_tests_helper.rb
module FourthTestsHelper
end

app/helpers/second_tests_helper.rb
module SecondTestsHelper
end

app/helpers/sixth_reviews_helper.rb
module SixthReviewsHelper
end

app/helpers/third_tests_helper.rb
module ThirdTestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :admin %><br>
    <%= f.check_box :admin %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<% @total4 = 0 %><% @total5 = 0 %>
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="row">
    <div id="formariol">
      <ul>
        <% if current_user.admin? %>
          <% @users.each do |user| %>
          <li class="col-sm-2">
          <h2>Equipo: <%= user.team %></h2>
          <%= link_to 'Ver prueba', user %>
            <% user.fourth_tests.each do |fourth_test| %>
              <% if fourth_test.fifth_reviews.present? %>
                <h5>Calificación de Video: </h5>
                  <%=  @l= fourth_test.fifth_reviews.average(:problem2).round(2) 
                       @m= fourth_test.fifth_reviews.average(:cliente2).round(2) 
                       @n= fourth_test.fifth_reviews.average(:propuesta2).round(2) 
                       @o= fourth_test.fifth_reviews.average(:ventajas2).round(2) 
                       @p= fourth_test.fifth_reviews.average(:monetizacion2).round(2) 
                       @q= fourth_test.fifth_reviews.average(:comunicacion2).round(2) 
                       @total4 = @l + @m + @n + @o + @p +@q %>
                  <% else %>
                  <td></td>
                   <% end %>

                   <% if fourth_test.sixth_reviews.present? %>
                <h5>Calificación de Pitch: </h5>
                  <%= @l= fourth_test.sixth_reviews.average(:problem3).round(2) 
                      @m= fourth_test.sixth_reviews.average(:cliente3).round(2) 
                      @n= fourth_test.sixth_reviews.average(:propuesta3).round(2) 
                      @o= fourth_test.sixth_reviews.average(:ventajas3).round(2) 
                      @p= fourth_test.sixth_reviews.average(:monetizacion3).round(2) 
                      @q= fourth_test.sixth_reviews.average(:comunicacion3).round(2) 
                      @total4 = @l + @m + @n + @o + @p +@q %>
                  <% else %>
                  <td></td>
                  <% end %>
            <% end %>
          </li>
          <% end %>
        <% else %>
          <% @usera.each do |user| %>
          <li class="col-sm-2">
          <h2>Equipo: <%= user.team %></h2>
          <%= link_to 'Ver prueba', user %>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
    </div>
  </div>
</div>

<!-- <h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th>team</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.team %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_registration_path %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> -->

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% @total = 0 %><% @total1 = 0 %><% @total2 = 0 %><% @total3 = 0 %><% @total4 = 0 %><% @total5 = 0 %>

<p id="notice"><%= notice %></p>

<div class="container">
    <div class="col-sm-10 col-sm-offset-1">
        <div class="row">
            <div id="formariol">
              <strong>Equipo:</strong>
              <h3><%= @user.team %></h3>
              <br>
              <div class="row">
                <div class="col-xs-4">
                  <%=@user.inte1 %> | | <%=@user.cuenta1 %><br><br>
              </div>
              <div class="col-xs-4">
                  <%=@user.inte2 %> | | <%=@user.cuenta2 %><br><br>
              </div>
              <div class="col-xs-4">
                  <%=@user.inte3 %> | | <%=@user.cuenta3 %><br><br>
              </div>
              <div class="col-xs-4">
                  <%=@user.inte4 %> | | <%=@user.cuenta4 %><br><br>
              </div>
              <div class="col-xs-4">
                  <%=@user.inte5 %> | | <%=@user.cuenta5 %><br><br>
              </div>
          </div>
          <ul>
           <% if @user.first_tests.blank? %>
           <%= link_to new_user_first_test_path(@user) do %>
           <li class="col-sm-2">
               <h2>Primera Prueba</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
           </li>
           <% end %>
           <% else %>
           <% @user.first_tests.each do |first_test| %>
           <li class="col-sm-2">
              <%= link_to edit_user_first_test_path(@user, first_test) do %>
              <h2>Primera Prueba</h2>
              <% if current_user.admin? %>
              <%= link_to "Calificar", user_first_test_path(@user, first_test) %>
              <% end %>
              <% if first_test.first_reviews.present? %>
              <% if current_user.admin? %>
              <h3>Calificación: </h3>
              <%= @total1= first_test.first_reviews.average(:info1).round(2) 
              @total1 %>
              <% else %>
              <td></td>
              <% end %>
              <% end %>
              <% end %>
              <% end %>
              <% end %>
          </li>


          <% if @user.second_tests.blank? %>
          <%= link_to new_user_second_test_path(@user) do %>
          <li class="col-sm-2">
           <h2>Segunda Prueba</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
       </li>
       <% end %>
       <% else %>
       <% @user.second_tests.each do |second_test| %>
       <li class="col-sm-2">
          <%= link_to edit_user_second_test_path(@user, second_test) do %>
          <h2>Segunda Prueba</h2>
          <% if current_user.admin? %>
          <%= link_to "Calificar", user_second_test_path(@user, second_test) %>
          <% end %>
          <% if second_test.second_reviews.present? %>
          <% if current_user.admin? %>
          <h3>Calificación: </h3>
          <%= @a = second_test.second_reviews.average(:problema1).round(2) 
          @b = second_test.second_reviews.average(:cliente1).round(2)
          @c = second_test.second_reviews.average(:alternativa1).round(2)
          @d = second_test.second_reviews.average(:solucion1).round(2)
          @e = second_test.second_reviews.average(:ventajas1).round(2)
          @total = @a + @b + @c + @d + @e

          @total
          %>
          <% else %>
          <td></td>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
          <% end %>
      </li>



      <% if @user.third_tests.blank? %>
      <%= link_to new_user_third_test_path(@user) do %>
      <li class="col-sm-2">
       <h2>Tercera Prueba</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
   </li>
   <% end %>
   <% else %>
   <% @user.third_tests.each do |third_test| %>
   <li class="col-sm-2">
      <%= link_to edit_user_third_test_path(@user, third_test) do %>
      <h2>Tercera Prueba</h2>
      <% if current_user.admin? %>
      <%= link_to "Calificar", user_third_test_path(@user, third_test) %>
      <% end %>
      <% if third_test.third_reviews.present? %>
      <% if current_user.admin? %>
      <h3>Calificación: </h3>
      <%= @f= third_test.third_reviews.average(:info2).round(2) 
      @g= third_test.third_reviews.average(:likes1).round(2)
      @h= third_test.third_reviews.average(:aprendizaje1).round(2)

      @total2= @f + @g + @h 
      @total2 %>
      <% else %>
      <td></td>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
  </li>

  <% if @user.fourth_tests.blank? %>
  <%= link_to new_user_fourth_test_path(@user) do %>
  <li class="col-sm-2">
   <h2>Cuarta Prueba</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
</li>
<% end %>
<% else %>
<% @user.fourth_tests.each do |fourth_test| %>
<li class="col-sm-2">
  <%= link_to edit_user_fourth_test_path(@user, fourth_test) do %>
  <h2>Cuarta Prueba</h2>
  <% if current_user.admin? %>
  <%= link_to "Calificar", user_fourth_test_path(@user, fourth_test) %>
  <% end %>
  <% if fourth_test.fourth_reviews.present? %>
  <% if current_user.admin? %>
  <h3>Calificación: </h3>
  <%= @i= fourth_test.fourth_reviews.average(:video).round(2)
  @j= fourth_test.fourth_reviews.average(:likes2).round(2)
  @k= fourth_test.fourth_reviews.average(:aprendizaje2).round(2)

  @total3= @i + @j + @k
  @total3 %>
  <% else %>
  <td></td>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
</li>

<% if current_user.admin? %>
<% if @user.fourth_tests.blank? %>
<%= link_to new_user_fourth_test_path(@user) do %>
<li class="col-sm-2">
   <h2>Video</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
</li>
<% end %>
<% else %>
<% @user.fourth_tests.each do |fourth_test| %>
<li class="col-sm-2">
  <%= link_to edit_user_fourth_test_path(@user, fourth_test) do %>
  <h2>Video</h2>
  <% if current_user.admin? %>
  <%= link_to "Calificar", user_fourth_test_path(@user, fourth_test, :anchor => "video") %>
  <% end %>
  <% if fourth_test.fifth_reviews.present? %>
  <h3>Calificación de Video: </h3>
  <%= @l= fourth_test.fifth_reviews.average(:problem2).round(2) 
  @m= fourth_test.fifth_reviews.average(:cliente2).round(2) 
  @n= fourth_test.fifth_reviews.average(:propuesta2).round(2) 
  @o= fourth_test.fifth_reviews.average(:ventajas2).round(2) 
  @p= fourth_test.fifth_reviews.average(:monetizacion2).round(2) 
  @q= fourth_test.fifth_reviews.average(:comunicacion2).round(2) 
  @total4 = @l + @m + @n + @o + @p +@q %>
  <% else %>
  <td></td>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
</li>
<% end %>

<% if current_user.admin? %>
<% if @user.fourth_tests.blank? %>
<%= link_to new_user_fourth_test_path(@user) do %>
<li class="col-sm-2">
   <h2>Pitch</h2>
           <% if current_user.admin? %>
            <h5>Aún no hay pruebas para calificar</h5>
           <% end %>
</li>
<% end %>
<% else %>
<% @user.fourth_tests.each do |fourth_test| %>
<li class="col-sm-2">
  <%= link_to edit_user_fourth_test_path(@user, fourth_test) do %>
  <h2>Pitch</h2>
  <% if current_user.admin? %>
  <%= link_to "Calificar", user_fourth_test_path(@user, fourth_test, :anchor => "pitch") %>
  <% end %>
  <% if fourth_test.sixth_reviews.present? %>
  <h3>Calificación de Pitch: </h3>
  <%= @l= fourth_test.sixth_reviews.average(:problem3).round(2) 
  @m= fourth_test.sixth_reviews.average(:cliente3).round(2) 
  @n= fourth_test.sixth_reviews.average(:propuesta3).round(2) 
  @o= fourth_test.sixth_reviews.average(:ventajas3).round(2) 
  @p= fourth_test.sixth_reviews.average(:monetizacion3).round(2) 
  @q= fourth_test.sixth_reviews.average(:comunicacion3).round(2) 
  @total5 = @l + @m + @n + @o + @p +@q %>
  <% else %>
  <td></td>
  <% end %>
  <% end %>
  <% end %>
  <% end %>
</li>
<% end %>

</ul>
</div>
</div>
</div>
</div>

<div class="container">
<h6><%= link_to "Descarga Formato de Reporte", '/reporte.xlsx' %></h6>
<h6><%= link_to "Descarga Boceto de Idea", '/boceto_de_idea.pdf' %></h6>
</div>


<% if current_user.admin? %>
<div class="col-sm-10 col-sm-offset-1">
  <div id="formario">
    <div class="row">
      <h2>Calificación de trabajo</h2>
      <h5 class="center"><%= @total + @total2 + @total3 + @total1 %></h5>
      <br>
      <h2>Calificación de Video</h2>
      <h5 class="center"><%= @total4 %></h5>
      <br>
      <h2>Calificación de Pitch Final</h2>
      <h5 class="center"><%= @total5 %></h5>
            <%= link_to 'Back', users_path %>


      <br>
    </div>
  </div>
</div>
<% end %>