config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :fourth_tests do
      resources :fourth_reviews
      resources :sixth_reviews
      resources :fifth_reviews
        end
    resources :third_tests do 
      resources :third_reviews
    end
    resources :second_tests do
      resources :second_reviews
    end
    resources :first_tests do
      resources :first_reviews
    end
  end

  

end

app/models/fifth_review.rb
class FifthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/first_review.rb
class FirstReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :first_test
end

app/models/first_test.rb
class FirstTest < ActiveRecord::Base
  belongs_to :user
  has_many :first_reviews, dependent: :destroy
  mount_uploader :info1
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.first_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fourth_review.rb
class FourthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/fourth_test.rb
class FourthTest < ActiveRecord::Base
  belongs_to :user
  has_many :fourth_reviews, dependent: :destroy
  has_many :fifth_reviews, dependent: :destroy
  has_many :sixth_reviews, dependent: :destroy
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.fourth_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fouth_review.rb
class FouthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/second_review.rb
class SecondReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :second_test
end

app/models/second_test.rb
class SecondTest < ActiveRecord::Base
  belongs_to :user
  has_many :second_reviews, dependent: :destroy
  mount_uploader :boceto
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.second_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/sixth_review.rb
class SixthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/third_review.rb
class ThirdReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :third_test
end

app/models/third_test.rb
class ThirdTest < ActiveRecord::Base
  belongs_to :user
  has_many :third_reviews, dependent: :destroy
  mount_uploader :info2
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.third_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :first_tests, dependent: :destroy
  has_many :second_tests, dependent: :destroy
  has_many :third_tests, dependent: :destroy
  has_many :fourth_tests, dependent: :destroy
  has_many :first_reviews, through: :tests, dependent: :destroy
  has_many :second_reviews, through: :tests, dependent: :destroy
  has_many :third_reviews, through: :tests, dependent: :destroy
  has_many :fourth_reviews, through: :tests, dependent: :destroy
  has_many :fifth_reviews, through: :tests, dependent: :destroy
  has_many :sixth_reviews, through: :tests, dependent: :destroy
end

app/controllers/sixth_reviews_controller.rb
class SixthReviewsController < ApplicationController
  before_action :set_sixth_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :filter_admin!
  before_action :set_fourth_test
  before_action :set_user

  # GET /sixth_reviews
  # GET /sixth_reviews.json
  def index
    @sixth_reviews = SixthReview.all
  end

  # GET /sixth_reviews/1
  # GET /sixth_reviews/1.json
  def show
  end

  # GET /sixth_reviews/new
  def new
    @sixth_review = SixthReview.new
  end

  # GET /sixth_reviews/1/edit
  def edit
  end

  # POST /sixth_reviews
  # POST /sixth_reviews.json
  def create
    @sixth_review = SixthReview.new(sixth_review_params)
    @fourth_test.user_id=current_user.id
    @sixth_review.fourth_test_id=@fourth_test.id

    if @sixth_review.save
      redirect_to user_path(@user)
    else
      render 'new'
    end

  end

  # PATCH/PUT /sixth_reviews/1
  # PATCH/PUT /sixth_reviews/1.json
  def update
    respond_to do |format|
      if @sixth_review.update(sixth_review_params)
        format.html { redirect_to @users, notice: 'Sixth review was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @sixth_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sixth_reviews/1
  # DELETE /sixth_reviews/1.json
  def destroy
    @sixth_review.destroy
    respond_to do |format|
      format.html { redirect_to sixth_reviews_url, notice: 'Sixth review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def filter_admin!
 authenticate_user!
 redirect_to root_path, alert: "Lo lamento, no tienes acceso" unless current_user.admin?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sixth_review
      @sixth_review = SixthReview.find(params[:id])
    end

    def set_fourth_test
      @fourth_test = FourthTest.find(params[:fourth_test_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sixth_review_params
      params.require(:sixth_review).permit(:user_id, :fourth_test_id, :problem3, :cliente3, :propuesta3, :ventajas3, :monetizacion3, :comunicacion3)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.where(admin: false).order("team asc")
    @usera = User.where(id: current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all.includes(:first_tests, :second_tests, :third_tests, :fourth_tests)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :admin, :team, :inte1, :inte2, :inte3, :inte4, :inte5, :cuenta1, :cuenta2, :cuenta3, :cuenta4, :cuenta5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_tests_helper.rb
module FirstTestsHelper
end

app/helpers/fourth_tests_helper.rb
module FourthTestsHelper
end

app/helpers/second_tests_helper.rb
module SecondTestsHelper
end

app/helpers/sixth_reviews_helper.rb
module SixthReviewsHelper
end

app/helpers/third_tests_helper.rb
module ThirdTestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sixth_reviews/_form.html.erb
<%= form_for([@user, @fourth_test, @sixth_review]) do |f| %>
  <% if @sixth_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sixth_review.errors.count, "error") %> prohibited this sixth_review from being saved:</h2>

      <ul>
      <% @sixth_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2>Fase <strong>6. PITCH FINAL</strong></h2>
  <hr class="blue">

<p class="center">Esta parte en unicamente para los finalistas. Ve el video y elige la opción que mejor describa cada rubro.</p>

<div class="field">
    <%= f.label :problema_oportunidad %><br>
  <%= f.select :problem3, [["El problema/oportunidad está bien definido y es fácil ver que es un problema/oportunidad relevante", 5], ["El problema/oportunidad es muy general y cuesta trabajo saber si es relevante o no", 3], ["Se nota claramente que el problema/oportunidad no es relevante", 0]]%>
  </div>
  <div class="field">
    <%= f.label :cliente_y_o_usuario %><br>
    <%= f.select :cliente3, [["Está claro quién es el cliente y quién es el usuario y es fácil identificar por qué ellos tienen el problema/oportunidad", 5], ["La descripción del cliente y/o usuario es muy general y es difícil de entender por qué tienen ellos el problema/oportunidad", 3], ["No está claro el cliente y/o usuario", 0]]%>
  </div>
  <div class="field">
    <%= f.label :propuesta_de_solucion %><br>
    <%= f.select :propuesta3, [["Describe de forma clara la solución, diciendo si es un producto o un servicio ", 5], ["Habla de la solución de forma genérica, no se entiende del todo de qué se trata", 3], ["No se entiende la solución planteada", 0]]%>
  </div>
  <div class="field">
    <%= f.label :ventajas_competitivas_diferenciadoras %><br>
<%= f.select :ventajas3, [["Las ventajas competitivas que proponen son relevantes y difíciles de copiar", 5], ["Las ventajas competitivas no son tan relevantes o son fáciles de copiar", 3], ["No demuestra ventajas competitivas que sean relevantes y cualquiera podría copiarlas", 0]]%>
  </div>
  <div class="field">
    <%= f.label :monetizacion %><br>
    <%= f.select :monetizacion3, [["El modelo de monetización es claro y propicia el escalamiento ", 5], ["El modelo de monetización no es claro o no propicia el escalamiento", 3], ["No habla del modelo de monetización", 0]]%>
  </div>
  <div class="field">
    <%= f.label :comunicacion %><br>
    <%= f.select :comunicacion3, [["El video está claro, convence y mueve a la acción", 5], ["El video está claro pero no convence ni mueve a la acción", 3], ["El video no está claro y no mueve ni llama a la acción", 0]]%>
  </div>

<br>  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sixth_reviews/edit.html.erb
<h1>Editing Sixth Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @sixth_review %> |
<%= link_to 'Back', sixth_reviews_path %>

app/views/sixth_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sixth Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Fourth test</th>
      <th>Problem3</th>
      <th>Cliente3</th>
      <th>Propuesta3</th>
      <th>Ventajas3</th>
      <th>Monetizacion3</th>
      <th>Comunicacion3</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sixth_reviews.each do |sixth_review| %>
      <tr>
        <td><%= sixth_review.user %></td>
        <td><%= sixth_review.fourth_test %></td>
        <td><%= sixth_review.problem3 %></td>
        <td><%= sixth_review.cliente3 %></td>
        <td><%= sixth_review.propuesta3 %></td>
        <td><%= sixth_review.ventajas3 %></td>
        <td><%= sixth_review.monetizacion3 %></td>
        <td><%= sixth_review.comunicacion3 %></td>
        <td><%= link_to 'Show', sixth_review %></td>
        <td><%= link_to 'Edit', edit_sixth_review_path(sixth_review) %></td>
        <td><%= link_to 'Destroy', sixth_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sixth review', new_sixth_review_path %>

app/views/sixth_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @sixth_review.user %>
</p>

<p>
  <strong>Fourth test:</strong>
  <%= @sixth_review.fourth_test %>
</p>

<p>
  <strong>Problem3:</strong>
  <%= @sixth_review.problem3 %>
</p>

<p>
  <strong>Cliente3:</strong>
  <%= @sixth_review.cliente3 %>
</p>

<p>
  <strong>Propuesta3:</strong>
  <%= @sixth_review.propuesta3 %>
</p>

<p>
  <strong>Ventajas3:</strong>
  <%= @sixth_review.ventajas3 %>
</p>

<p>
  <strong>Monetizacion3:</strong>
  <%= @sixth_review.monetizacion3 %>
</p>

<p>
  <strong>Comunicacion3:</strong>
  <%= @sixth_review.comunicacion3 %>
</p>

<%= link_to 'Edit', edit_sixth_review_path(@sixth_review) %> |
<%= link_to 'Back', sixth_reviews_path %>