config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'welcome#index'

  resources :users do
    resources :fourth_tests do
      resources :fourth_reviews
      resources :sixth_reviews
      resources :fifth_reviews
        end
    resources :third_tests do 
      resources :third_reviews
    end
    resources :second_tests do
      resources :second_reviews
    end
    resources :first_tests do
      resources :first_reviews
    end
  end

  

end

app/models/fifth_review.rb
class FifthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/first_review.rb
class FirstReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :first_test
end

app/models/first_test.rb
class FirstTest < ActiveRecord::Base
  belongs_to :user
  has_many :first_reviews, dependent: :destroy
  mount_uploader :info1
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.first_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fourth_review.rb
class FourthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/fourth_test.rb
class FourthTest < ActiveRecord::Base
  belongs_to :user
  has_many :fourth_reviews, dependent: :destroy
  has_many :fifth_reviews, dependent: :destroy
  has_many :sixth_reviews, dependent: :destroy
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.fourth_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/fouth_review.rb
class FouthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/second_review.rb
class SecondReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :second_test
end

app/models/second_test.rb
class SecondTest < ActiveRecord::Base
  belongs_to :user
  has_many :second_reviews, dependent: :destroy
  mount_uploader :boceto
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.second_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/sixth_review.rb
class SixthReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :fourth_test
end

app/models/third_review.rb
class ThirdReview < ActiveRecord::Base
  belongs_to :user
  belongs_to :third_test
end

app/models/third_test.rb
class ThirdTest < ActiveRecord::Base
  belongs_to :user
  has_many :third_reviews, dependent: :destroy
  mount_uploader :info2
validate :just_one_post, :on => :create 


protected  
def just_one_post 
	if user.third_tests.count >= 1 
	errors.add(:user_id, "El usuario ya tiene un test") 
  end 
end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :first_tests, dependent: :destroy
  has_many :second_tests, dependent: :destroy
  has_many :third_tests, dependent: :destroy
  has_many :fourth_tests, dependent: :destroy
  has_many :first_reviews, through: :tests, dependent: :destroy
  has_many :second_reviews, through: :tests, dependent: :destroy
  has_many :third_reviews, through: :tests, dependent: :destroy
  has_many :fourth_reviews, through: :tests, dependent: :destroy
  has_many :fifth_reviews, through: :tests, dependent: :destroy
  has_many :sixth_reviews, through: :tests, dependent: :destroy
end

app/controllers/third_reviews_controller.rb
class ThirdReviewsController < ApplicationController
  before_action :set_third_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :filter_admin!
  before_action :set_third_test
  before_action :set_user

  # GET /third_reviews
  # GET /third_reviews.json
  def index
    @third_reviews = ThirdReview.all
  end

  # GET /third_reviews/1
  # GET /third_reviews/1.json
  def show
  end

  # GET /third_reviews/new
  def new
    @third_review = ThirdReview.new
  end

  # GET /third_reviews/1/edit
  def edit
  end

  # POST /third_reviews
  # POST /third_reviews.json
  def create
    @third_review = ThirdReview.new(third_review_params)
    @third_test.user_id=current_user.id
    @third_review.third_test_id=@third_test.id

    if @third_review.save
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  # PATCH/PUT /third_reviews/1
  # PATCH/PUT /third_reviews/1.json
  def update
    respond_to do |format|
      if @third_review.update(third_review_params)
        format.html { redirect_to @users, notice: 'Third review was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @third_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /third_reviews/1
  # DELETE /third_reviews/1.json
  def destroy
    @third_review.destroy
    respond_to do |format|
      format.html { redirect_to third_reviews_url, notice: 'Third review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def filter_admin!
 authenticate_user!
 redirect_to root_path, alert: "Lo lamento, no tienes acceso" unless current_user.admin?
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_third_review
      @third_review = ThirdReview.find(params[:id])
    end

    def set_third_test
      @third_test = ThirdTest.find(params[:third_test_id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def third_review_params
      params.require(:third_review).permit(:user_id, :third_test_id, :info2, :likes1, :aprendizaje1)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.where(admin: false).order("team asc")
    @usera = User.where(id: current_user.id)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @users = User.all.includes(:first_tests, :second_tests, :third_tests, :fourth_tests)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @users }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :admin, :team, :inte1, :inte2, :inte3, :inte4, :inte5, :cuenta1, :cuenta2, :cuenta3, :cuenta4, :cuenta5)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/first_tests_helper.rb
module FirstTestsHelper
end

app/helpers/fourth_tests_helper.rb
module FourthTestsHelper
end

app/helpers/second_tests_helper.rb
module SecondTestsHelper
end

app/helpers/third_reviews_helper.rb
module ThirdReviewsHelper
end

app/helpers/third_tests_helper.rb
module ThirdTestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/third_reviews/_form.html.erb
<%= form_for([@user, @third_test, @third_review]) do |f| %>
  <% if @third_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@third_review.errors.count, "error") %> prohibited this third_review from being saved:</h2>

      <ul>
      <% @third_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<h2>Fase <strong>3. PROTOTIPADO</strong></h2>
  <hr class="blue">

  <p class="center">Para este momento, el equipo ya validó el problema y al cliente. Lo que están validando en esta fase es la solución con un prototipado de baja fidelidad, que es una infografía. <br><br>

Revisa la infografía y califica el contenido, el diseño y las llamadas a la acción. <br><br></p>

  <div class="field">
    <%= f.label :Contenido_de_la_infografía %><br>
    <!-- <%#= f.number_field :info2 %> -->
    <%= f.select :info2, [["La infografía expone de manera creativa y clara la propuesta de solución. Se nota el problema/oportunidad que está atendiendo y las ventajas competitivas son claras y diferenciadoras.", 10], ["La infografía expone de manera simple la solución. Las ventajas competitivas no están claras del todo claras y el problema/oportunidad atendido es confuso.", 5], ["La infografía expone la solución sin dejar ver las ventajas competitivas ni el problema/oportunidad atendido.", 0]]%>
  </div>
  <div class="field">
    <%= f.label :Diseño_y_llamada_a_la_acción %><br>
    <!-- <%#= f.number_field :likes1 %> -->
    <%= f.select :likes1, [["El diseño es atractivo, comunica e invita a la reflexión o interés y tiene llamada a la acción clara", 10], ["El diseño es poco atractivo y comunica medianamente la situación que se quiere ejemplificar y tiene una llamada a la acción poco clara", 5], ["El diseño no es atractivo y no comunica ni medianamente lo el mensaje objetivo y no tiene llamada a la acción", 0]]%>
  </div>
  <div class="field">
    <%= f.label :aprendizaje %><br>
    <!-- <%#= f.number_field :aprendizaje1 %> -->
    <%= f.select :aprendizaje1, [["Los aprendizajes que expone son verdaderamente relevantes para la propuesta", 5], ["Los aprendizajes que expone no invita a hacer modificaciones a la propuesta", 3], ["No expone aprendizajes o escribió cualquier cosa", 0]]%>
  </div>

  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/third_reviews/edit.html.erb
<h1>Editing Third Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @third_review %> |
<%= link_to 'Back', third_reviews_path %>

app/views/third_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Third Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Third test</th>
      <th>Info2</th>
      <th>Likes1</th>
      <th>Aprendizaje1</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @third_reviews.each do |third_review| %>
      <tr>
        <td><%= third_review.user %></td>
        <td><%= third_review.third_test %></td>
        <td><%= third_review.info2 %></td>
        <td><%= third_review.likes1 %></td>
        <td><%= third_review.aprendizaje1 %></td>
        <td><%= link_to 'Show', third_review %></td>
        <td><%= link_to 'Edit', edit_third_review_path(third_review) %></td>
        <td><%= link_to 'Destroy', third_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Third review', new_third_review_path %>

app/views/third_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @third_review.user %>
</p>

<p>
  <strong>Third test:</strong>
  <%= @third_review.third_test %>
</p>

<p>
  <strong>Info2:</strong>
  <%= @third_review.info2 %>
</p>

<p>
  <strong>Likes1:</strong>
  <%= @third_review.likes1 %>
</p>

<p>
  <strong>Aprendizaje1:</strong>
  <%= @third_review.aprendizaje1 %>
</p>

<%= link_to 'Edit', edit_third_review_path(@third_review) %> |
<%= link_to 'Back', third_reviews_path %>